filtres:
    resource: "@filtresBundle/Resources/config/routing.yml"
    prefix:   /

idle_game:
    resource: "@IdleGameBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
