<?php

namespace IdleGameBundle\Repository;

/**
 * categoriesForum
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriesForum extends \Doctrine\ORM\EntityRepository
{
}
