<?php

namespace IdleGameBundle\Repository;

/**
 * Articles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dataUser extends \Doctrine\ORM\EntityRepository
{

}