<?php

namespace IdleGameBundle\Repository;

/**
 * equipement
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipement extends \Doctrine\ORM\EntityRepository
{
}
