<?php

namespace IdleGameBundle\Repository;

/**
 * topic
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class topic extends \Doctrine\ORM\EntityRepository
{
}
