game_idle_game:
    path:     /
    defaults: { _controller: IdleGameBundle:Default:index }

game_idle_save:
    path:     /save
    defaults: { _controller: IdleGameBundle:Default:save }

game_idle_forum:
    path:     /forum
    defaults: { _controller: IdleGameBundle:Default:forum }

game_idle_topic:
    path:     /topic/{id}
    defaults: { _controller: IdleGameBundle:Default:topic }

game_idle_post:
    path:     /post/{id}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:post }

game_idle_newtopic:
    path:     /newtopic/{id}
    defaults: { _controller: IdleGameBundle:Default:newTopic }

game_idle_newpost:
    path:     /newpost/{id}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:newPost }

game_idle_editpost:
    path:     /editpost/{id}/{idTopic}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:editPost }

game_idle_edittopic:
    path:     /edittopic/{idTopic}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:editTopic}

game_idle_deletepost:
    path:     /deletepost/{id}/{idTopic}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:deletePost }

game_idle_deletetopic:
    path:     /deletetopic/{idTopic}/{idCateg}
    defaults: { _controller: IdleGameBundle:Default:deleteTopic }

game_idle_highscore:
    path:     /highscore
    defaults: { _controller: IdleGameBundle:Default:highscore }

game_idle_backoffice_index:
    path:     /admin/backindex
    defaults: { _controller: IdleGameBundle:Default:backIndex }

game_idle_backoffice_players:
    path:     /admin/backplayers
    defaults: { _controller: IdleGameBundle:Default:backPlayers }

game_idle_backoffice_player:
    path:     /admin/backplayer/{id}
    defaults: { _controller: IdleGameBundle:Default:backPlayer }

game_idle_landing:
    path:     /landing
    defaults: { _controller: IdleGameBundle:Default:landing }

game_idle_contact:
    path:     /contact
    defaults: { _controller: IdleGameBundle:Default:contact }

game_idle_equip:
    path:     /equip
    defaults: { _controller: IdleGameBundle:Default:saveEquip }

game_idle_inventory:
    path:     /inventory
    defaults: { _controller: IdleGameBundle:Default:showInventory }

game_idle_equipIt:
    path:     /equipIt
    defaults: { _controller: IdleGameBundle:Default:equipIt }